{% set name = "us" %}
{% set version = "2.0.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "fc11dd4592d7329f4b5d83040ea9ed1acbba57e512d5a3780a5a8285505cc36e" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  entry_points:
    - states = us.cli.states:main
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - jellyfish ==0.5.6
    - setuptools

test:
  imports:
    - us
    - us.cli

  commands:
    - states --help

about:
  home: https://github.com/unitedstates/python-us
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: US state meta information and other fun stuff
  dev_url: https://github.com/unitedstates/python-us

extra:
  recipe-maintainers:
    - pmlandwehr
